// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Tesis_EPICAI.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211005053134_inital")]
    partial class inital
    {
        
    }
}
